POST http://localhost:8080/user/
Content-Type: application/json

{
    "name" : "testUser",
    "dateOfBirth" : "13.12.2020"
}

POST http://localhost:8080/user/
Content-Type: application/json

{
    "name" : "testUser2",
    "dateOfBirth" : "13.12.2020"
}
GET http://localhost:8080/user/

GET http://localhost:8080/user/1

DELETE http://localhost:8080/user/1

GET http://localhost:8080/user/




POST http://localhost:8080/product/
Content-Type: application/json

{
    "name" : "testProduct",
    "price" : "145"
}

POST http://localhost:8080/product/
Content-Type: application/json

{
    "name" : "testProduct2",
    "price" : "145"
}

POST http://localhost:8080/product/
Content-Type: application/json

{
    "name" : "testProduct3",
    "price" : "145"
}

GET http://localhost:8080/product/

GET http://localhost:8080/product/1

DELETE http://localhost:8080/product/1

GET http://localhost:8080/product/



POST http://localhost:8080/package/
{
    "products" : [
    {
        "id": 2,
        "name": "testProduct2",
        "price": 145
    },
    {
        "id": 3,
        "name": "testProduct3",
        "price": 145
    }
],
    "sale" : "15"
}

POST http://localhost:8080/package/
{
    "products" : [
    {
        "id": 2,
        "name": "testProduct2",
        "price": 145
    },
    {
        "id": 3,
        "name": "testProduct3",
        "price": 145
    }
],
    "sale" : "45"
}

GET http://localhost:8080/package/

GET http://localhost:8080/package/2

DELETE http://localhost:8080/package/2

GET http://localhost:8080/package/


