services:
  backend:
    build: .
    container_name: eshop_backend
    ports:
      - "8080:8080"
    links:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://eshopDB_postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=eshopDbPass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  postgres:
    image: postgres:alpine
    container_name: eshopDB_postgres
    environment:
      POSTGRES_PASSWORD: eshopDbPass
      POSTGRES_USER: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

